development:
  clients:
    default:
      database: url_shortner_dev
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
test: 
  clients:
    default:
      database: url_shortener_test_db
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1