development:
  clients:
    default:
      database: url_shortener_dev_db
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
test: 
  clients:
    default:
      database: url_shortener_test_db
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
docker:
  clients:
    default:
      database: url_shortener_test_db
      hosts:
        - mongodb:27017
      options:
        server_selection_timeout: 5